# GitHub Actions Workflow for bundling production plugin zip file.

name: Create WP production plugin zip file

on:
  push:
    tags:
      - "*"

jobs:
  build-plugin-zip-asset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP 8.0
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install dependencies
        run: composer install --no-dev --ignore-platform-reqs --prefer-dist --no-scripts --optimize-autoloader

      ## I have commented the below because the project is not using any JS task runner yet. 
      # - name: Install nodejs dependencies
      #   run: npm install

      # - name: Generate production build
      #   run: npm run production

      - name: Clean unneeded files
        run: |
          [ -f .gitattributes ] && rm .gitattributes
          [ -d .github ] && rm -r .github
          [ -d .git ] && rm -r .git
          [ -f .gitignore ] && rm .gitignore
          [ -f phpcs.xml ] && rm phpcs.xml
          [ -f composer.json ] && rm composer.json
          [ -f composer.lock ] && rm composer.lock
          [ -f readme.md ] && rm readme.md

      - name: Create directory for artifacts
        run: mkdir custom-content-scraper

      - name: Move files to custom-content-scraper directory
        run: rsync -av --progress --exclude=custom-content-scraper . custom-content-scraper/

      - name: Create Artifact
        run: zip -qq -r "custom-content-scraper.zip" custom-content-scraper/

      - name: Upload release attachment
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: custom-content-scraper.zip
          tag: ${{ github.ref_name }}
          overwrite: true